use_frameworks!

platform :ios, '10.0'

target 'HHTabBarController_Example' do
  pod 'HHTabBarController', :path => '../'

  target 'HHTabBarController_Tests' do
    inherit! :search_paths

    
  end
end
